[install]
is_configured = 0
state_change_requires_restart = true
build = 14

[ui]
is_visible = false
label = TA for Trellix DB A07

[launcher]
author = NGS,Sangpt
description = Technical Add-on for A07 Trellix Database Security Alert 
version = 1.0

[package]
id = TA-cef_TrellixDB
check_for_updates = true
